### ISSUE TITLE
Migrate scala-client to SDK.v3 + libuast.v3

### ISSUE THREAD

**Issue by bzz** [bblfsh/scala-client#83]
An umbrella issue for client migration to new SDK. 

Takes similar approach to bblfsh/client-python. but aims to avoid having [all the changes in a single PR](https://github.com/bblfsh/client-python/pull/128), so will be broken down.

 - [x] SDK.v2 - parse API
   - [x] `parse()` impl, that uses new `protocol.v2`
   - [x] `decode()` impl, so the binary wire protocol can be read (on Go side)
   - [x] `root()` impl, so the decoded (on Go side) UAST can be exposed to JVM
   - [x] `load()` impl, so the Go-backed UAST can be transferred to host JVM memory #91 
   - [x] `encode()` impl. Reverse: JVM memory objects transferred to Go 
   - [x] expose mode argument for parse (native, annotated, semantic) #111
 - [x] SDK.v2 - filter API
   - [x] `iterator()` impl, so UAST can be iterated with and without loading it to JVM #106
   - [x] `filter()` impl, so XPath filtering works #109 
            take [early feedback on API](https://reviewable.io/reviews/bblfsh/scala-client/97#-LjMH6RtA3Mz0RtfWryx) into account 
   - [x] `Context` impl (JVM-side factory), so multiple concurrent `filter()` calls from the client are supported 
 - [x] SDK.v2 - list languages API
    Support for languages/version request (as soon as https://github.com/bblfsh/sdk/pull/400 is released)
 - [x] doc: add JNI debugging instructions #115 
 - [x] doc: update API examples in README and CLI tool
 - [x] ~investigate JNI warnings~ moved to #112 
 - [x] ~enable timeouts at v2 API again~ moved to #100
 - [x] ~CI: refactor to multiple modular jobs (tests, releases per-platform, etc)~ moved to #87

**Comment by bzz** [comment]
### New API example

Protocol.v2 response is protobuf-like encoded binary blob, so libuast now provides a method to `decode()` it on the Go side. Decoding will result only in in-memory UAST representation on the Go side, thus in order to be exposed to the host environment (JVM) as objects - the root node is also needs to `load()`ed.

Examples below use explicit type excessively in order to highlight the API internals, real applications \w same code will be more concise.

#### decode + load (Go->JVM)
```scala
import org.bblfsh.client.v2.*

// parse
//// read the binary UASTv2
val resp = client.parse(fileName, fileContent)

//// decode it, UAST is backed by Go
val ctx: ContextExt = resp.uast.decode()
val rootNode: NodeExt = ctx.root()

//// load the UAST from Go to JVM
val rootJvm: java.util.TreeMap[String, _] = rootNode.load()
```

#### encode (JVM -> Go -> JVM)
Opposite to decode: takes host (JVM) in-memory object tree and propagates it to the Go memory, where it serializes it to the bytes in protobuf-like wire format.
```scala
val encodedBytes: ByteBuffer = ctx.encode(rootNode, 0)
```

#### Iterate UAST (JVM)
TBD
```scala
// iterate the tree from
rootJvm
```

#### Query (Go->JVM)
TBD
```scala
```

**Comment by dennwc** [comment]
Maybe we can call `NodeExt` just `Node` (and same for `Context`)? Native nodes will be `Map[string, _]` (or whatever), so we won't need a native node type (opposed to `NodeExt`).

Also, the `Context` work is mentioned in the `filter`, but it is required to make `decode` work, so it probably belongs to that task group.

**Comment by bzz** [comment]
Thank you for the suggestion! I assumed that it will be simpler to make the decode part work first, with a global context.

**Comment by bzz** [comment]
https://github.com/bblfsh/client-scala/issues/83#issuecomment-493980921 updated to include better type names and USAT iteration example.

**Comment by bzz** [comment]
A pre-release RC1 was cut from the current state of v2 migration https://github.com/bblfsh/scala-client/releases/tag/v2.0-rc1

**Comment by bzz** [comment]
Update: [RC3](https://github.com/bblfsh/scala-client/releases/tag/v2.0.0-rc3) has been published.

**Comment by bzz** [comment]
The only missing part before doing v2.0.0 release is a developer documentation!
Will submit a PR first thing tomorrow and start preparing a release notes.

**Comment by bzz** [comment]
Everything seems to be ready for initial release 🎉
